### ISSUE TITLE
SPO mode tab missing

### ISSUE THREAD

**Issue by romainbou** [tuneinsight/glowing-bear-medco#22]
Since #19 with only the role SPO (survival_query) the analysis tab is missing
![Screenshot from 2022-05-14 10-45-44](https://user-images.githubusercontent.com/725345/168418476-47cbfd3c-a302-45ca-a7d7-2cbc94df4cfd.png)
![Screenshot from 2022-05-14 10-45-28](https://user-images.githubusercontent.com/725345/168418479-3ab2e5f1-74a7-4b0e-ba6a-3e1b3970f0aa.png)

**Comment by jimmydjabali** [comment]
The issue exists in `main` but seems to be fixed in https://github.com/tuneinsight/glowing-bear-medco/pull/20

![image](https://user-images.githubusercontent.com/10889224/168564433-258f975e-4220-4316-bce5-3b1127efdecd.png)
