### ISSUE TITLE
Closing a histogram does not have a lasting effect

### ISSUE THREAD

**Issue by Fasjul** [tuneinsight/glowing-bear-medco#47]
Closing a histogram does not have a lasting effect: After switching back to the cohort building tab and returning to the Statistics Results, the histogram reappears.

This information needs to be saved within the angular service linked to the explore statistics. Whenever a new query will be launched this information will need to be cleared. When a user switches from the result tab this information will need to be fetched in order to determine what histogram to display.

**Comment by f-marino** [comment]
Related to this, when running a new query, after clicking the run button, the number of patients of the previous query should be hidden right away while waiting for the new result

<img width="650" alt="image" src="https://user-images.githubusercontent.com/7016414/189936231-d5ce7697-c501-43b4-bdb1-8515d71c2d2a.png">

**Comment by f-marino** [comment]
#74 partially fixes the problem. Switching go and back between the tabs before running a new query will still make the histogram reappear, but at least now when a new statistics query is launched the old histogram is automatically cleared and won't reappear.
