### ISSUE TITLE
A query should be able to run if it contains at least an analyte

### ISSUE THREAD

**Issue by Fasjul** [tuneinsight/glowing-bear-medco#48]
after discussion we believe that the analyte should be added to the cohort definition with the following options:

The Analytes are bound to each other with an OR. This forms the Analyte group.
Motivation: If we have two analytes, using an OR is the only way to have the Analytes in the query definition without having them interacting negatively with each other.

The Analytes group is bound to the rest of the query with an AND.
Motivation: speeding up the "fetching patients conforming to the cohort definition" step by restricting it to patients that have a result to bring.

Each analyte is bound with an AND with option "same instance" on elements that are related to the same Concept as the analyte is.
Motivation: Allows to filter on the other options such as test kit.
Alternative 1: Change the i2b2/GB logic so the "same instance" is smarter and never yields 0 for heterogeneous concept selection. Use "same instance" by default.
Alternative 2: distribute the analytes to the cohort selection panels. Potentially duplicate the panels... To investigate.

**Comment by f-marino** [comment]
I don't understand how the title and the description match.

From what we discussed with Harald, the only thing they need is indeed the possibility to run the statistics query on the whole dataset, which is what the title says. Then all the AND/OR/same instance stuff I don't really understand.

**Comment by Fasjul** [comment]
"run the statistics query on the whole dataset" I agree, but then the mid-query patient set will include all patients (i.e also the ones who don't have an observation for the selecte analyte), and try to look for the analyte's result for all of them.
This is suboptimal compared to using the analyte itself as a constraint (which produces headaches when we have several analytes).

Example : 3 of my 10 000 000 patients had a "oxygen in blood" test. The naive approach runs a no-constraint query, returning the whole 10 000 000 patient list, then goes fetch the "oxygen in blood" result for all of them (which will return something only for the 3 patients), which is way longer to process than having the patient list with only 3 entries.
