### ISSUE TITLE
[SPO] Analysis - the "Run" button remain disabled when changing parameters

### ISSUE THREAD

**Issue by romainbou** [tuneinsight/glowing-bear-medco#73]
Parameters that should re-enable the Run button but doesn't:
- Reset button
- Time limit
- Changing the selected saved cohort

https://user-images.githubusercontent.com/725345/191540513-9a5038a5-c431-4c71-84e9-d78301500b85.mp4

While dropping a concept or changing to another tab seems to re-enable it.

**Comment by f-marino** [comment]
@romainbou which dataset are you using?

**Comment by f-marino** [comment]
Couldn't reproduce the issue but this should fix it https://github.com/tuneinsight/glowing-bear-medco/pull/75
