### ISSUE TITLE
Server-side errors upon first data loading on LeoMed

### ISSUE THREAD

**Issue by T-Blatter** [tuneinsight/glowing-bear-medco#76]
TI4Health instance on LeoMed is now connected to both the CHUV_BIOREF and SIS_BIOREF with some initial data loaded.

Now after running the query "Chloride in Serum or Plasma; no constraints", a variety of errors appear.

Screenshot from zoom call with Franz Liem:
<img width="1110" alt="Bildschirmfoto 2022-09-22 um 11 25 57" src="https://user-images.githubusercontent.com/66185582/191916275-84e191fd-1740-4566-af0d-b0e4bd3f974f.png">

**Comment by T-Blatter** [comment]
List of errors:

- Error: Error during explore query _query-hash_
- Error while querying the data source
- A server-side 504 error occurred (2x)
- Error: undefined

**Comment by f-marino** [comment]
This is probably an error due to some connection issue between chuv and sis, so it is not something we can fix. The new update we released on Friday will make it easier to identify the source of this kind of errors.
